scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
	
})
let mySprite = sprites.create(img`
    .............ffffff.............
    ............f111111f............
    ............f1f11f1f............
    ............f111111f............
    ............f1f11f1f............
    ............f11ff11f............
    .............ffffff.............
    ...........ffffffffff...........
    ...........ffffffffff...........
    ..........ffffffffffff..........
    .........ffffffffffffff.........
    ........ffffffffffffffff........
    .......ffffffffffffffffff.......
    .......fff.ffffffffff.fff.......
    .......fff.ffffffffff.fff.......
    .......fff.ffffffffff.fff.......
    .......fff.ffffffffff.fff.......
    .......fff.ffffffffff.fff.......
    .......111.ffffffffff.111.......
    .......111.ffffffffff.111.......
    ...........ffffffffff...........
    ...........ffffffffff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    ...........fff....fff...........
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite)
tiles.setCurrentTilemap(tilemap`level1`)
